In [6]:
## Data analysis - chapter 3
import pandas as pd
import numpy as np
import matplotlib as plt
#Steps in data analysis
#1.get the dataset 
df = pd.read_csv(r'C:\Users\SRIVIDHYA\Desktop\breastcancer.csv')
df.shape
#2. to find the rows and columns
df.dtypes
#3.to find the data types
df.info()
#4. to find the number of non null values and data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
id                         569 non-null int64
diagnosis                  569 non-null object
radius_mean                569 non-null float64
texture_mean               569 non-null float64
perimeter_mean             569 non-null float64
area_mean                  569 non-null float64
smoothness_mean            569 non-null float64
compactness_mean           569 non-null float64
concavity_mean             569 non-null float64
concave points_mean        569 non-null float64
symmetry_mean              569 non-null float64
fractal_dimension_mean     569 non-null float64
radius_se                  569 non-null float64
texture_se                 569 non-null float64
perimeter_se               569 non-null float64
area_se                    569 non-null float64
smoothness_se              569 non-null float64
compactness_se             569 non-null float64
concavity_se               569 non-null float64
concave points_se          569 non-null float64
symmetry_se                569 non-null float64
fractal_dimension_se       569 non-null float64
radius_worst               569 non-null float64
texture_worst              569 non-null float64
perimeter_worst            569 non-null float64
area_worst                 569 non-null float64
smoothness_worst           569 non-null float64
compactness_worst          569 non-null float64
concavity_worst            569 non-null float64
concave points_worst       569 non-null float64
symmetry_worst             569 non-null float64
fractal_dimension_worst    569 non-null float64
Unnamed: 32                0 non-null float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [2]:
df.describe(include =[np.number]).T
#5. to get the summary statistics and transporse it for better readability

,count,mean,std,min,25%,50%,75%,max
id,569.0,3.037183e+07,1.250206e+08,8670.000000,869218.000000,906024.000000,8.813129e+06,9.113205e+08
radius_mean,569.0,1.412729e+01,3.524049e+00,6.981000,11.700000,13.370000,1.578000e+01,2.811000e+01
texture_mean,569.0,1.928965e+01,4.301036e+00,9.710000,16.170000,18.840000,2.180000e+01,3.928000e+01
perimeter_mean,569.0,9.196903e+01,2.429898e+01,43.790000,75.170000,86.240000,1.041000e+02,1.885000e+02
area_mean,569.0,6.548891e+02,3.519141e+02,143.500000,420.300000,551.100000,7.827000e+02,2.501000e+03
smoothness_mean,569.0,9.636028e-02,1.406413e-02,0.052630,0.086370,0.095870,1.053000e-01,1.634000e-01
compactness_mean,569.0,1.043410e-01,5.281276e-02,0.019380,0.064920,0.092630,1.304000e-01,3.454000e-01
concavity_mean,569.0,8.879932e-02,7.971981e-02,0.000000,0.029560,0.061540,1.307000e-01,4.268000e-01
concave points_mean,569.0,4.891915e-02,3.880284e-02,0.000000,0.020310,0.033500,7.400000e-02,2.012000e-01
symmetry_mean,569.0,1.811619e-01,2.741428e-02,0.106000,0.161900,0.179200,1.957000e-01,3.040000e-01
fractal_dimension_mean,569.0,6.279761e-02,7.060363e-03,0.049960,0.057700,0.061540,6.612000e-02,9.744000e-02
radius_se,569.0,4.051721e-01,2.773127e-01,0.111500,0.232400,0.324200,4.789000e-01,2.873000e+00
texture_se,569.0,1.216853e+00,5.516484e-01,0.360200,0.833900,1.108000,1.474000e+00,4.885000e+00
perimeter_se,569.0,2.866059e+00,2.021855e+00,0.757000,1.606000,2.287000,3.357000e+00,2.198000e+01
area_se,569.0,4.033708e+01,4.549101e+01,6.802000,17.850000,24.530000,4.519000e+01,5.422000e+02
smoothness_se,569.0,7.040979e-03,3.002518e-03,0.001713,0.005169,0.006380,8.146000e-03,3.113000e-02
compactness_se,569.0,2.547814e-02,1.790818e-02,0.002252,0.013080,0.020450,3.245000e-02,1.354000e-01
concavity_se,569.0,3.189372e-02,3.018606e-02,0.000000,0.015090,0.025890,4.205000e-02,3.960000e-01
concave points_se,569.0,1.179614e-02,6.170285e-03,0.000000,0.007638,0.010930,1.471000e-02,5.279000e-02
symmetry_se,569.0,2.054230e-02,8.266372e-03,0.007882,0.015160,0.018730,2.348000e-02,7.895000e-02
fractal_dimension_se,569.0,3.794904e-03,2.646071e-03,0.000895,0.002248,0.003187,4.558000e-03,2.984000e-02
radius_worst,569.0,1.626919e+01,4.833242e+00,7.930000,13.010000,14.970000,1.879000e+01,3.604000e+01
texture_worst,569.0,2.567722e+01,6.146258e+00,12.020000,21.080000,25.410000,2.972000e+01,4.954000e+01
perimeter_worst,569.0,1.072612e+02,3.360254e+01,50.410000,84.110000,97.660000,1.254000e+02,2.512000e+02
area_worst,569.0,8.805831e+02,5.693570e+02,185.200000,515.300000,686.500000,1.084000e+03,4.254000e+03
smoothness_worst,569.0,1.323686e-01,2.283243e-02,0.071170,0.116600,0.131300,1.460000e-01,2.226000e-01
compactness_worst,569.0,2.542650e-01,1.573365e-01,0.027290,0.147200,0.211900,3.391000e-01,1.058000e+00
concavity_worst,569.0,2.721885e-01,2.086243e-01,0.000000,0.114500,0.226700,3.829000e-01,1.252000e+00
concave points_worst,569.0,1.146062e-01,6.573234e-02,0.000000,0.064930,0.099930,1.614000e-01,2.910000e-01
symmetry_worst,569.0,2.900756e-01,6.186747e-02,0.156500,0.250400,0.282200,3.179000e-01,6.638000e-01
fractal_dimension_worst,569.0,8.394582e-02,1.806127e-02,0.055040,0.071460,0.080040,9.208000e-02,2.075000e-01
Unnamed: 32,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.describe(include =[np.object,pd.Categorical] ).T
#string names can be replaced with python objects when referring to dtypes
#
#6.categorical coulmns are going to be np.object or pd.categorical 

#pandas categorical datatype  is pd.categorical(values,categories,ordered) for categorical data and any value that is present is categories and in values will be treated as NaN
#ordered = true means to

          count unique top freq
diagnosis   569      2   B  357

In [4]:
#example for categorical in pandas 
cat = pd.Categorical(["a", "c", "c", np.nan], categories=["b", "a", "c"])
df = pd.DataFrame({"cat":cat, "s":["a", "c", "c", np.nan]})

cat
df

df["cat"].describe()

count     3
unique    2
top       c
freq      2
Name: cat, dtype: object

In [34]:
#creating and maintaining a data dictionary ie table of meta data(columns ) and info abt it like abbrevations of the columns

In [5]:
#changing the data  type to categorical data type reduces the memory storage
df.dtypes

cat    category
s        object
dtype: object

In [6]:
df.head(10)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN
5,843786,M,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,...,23.75,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440,NaN
6,844359,M,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,...,27.66,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368,NaN
7,84458202,M,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,...,28.14,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510,NaN
8,844981,M,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,...,30.73,106.20,739.3,0.1703,0.5401,0.5390,0.2060,0.4378,0.10720,NaN
9,84501001,M,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,...,40.68,97.65,711.4,0.1853,1.0580,1.1050,0.2210,0.4366,0.20750,NaN

In [7]:
#delete the not needed column
del df['Unnamed: 32']

KeyError: 'Unnamed: 32'

In [8]:
#memory usage savings by changing the data type
# though here in this example changing data type doesnt have impact this is an important step in data analysis
cols_new =['fractal_dimension_worst','smoothness_worst','texture_worst','diagnosis']
cols2 = df.loc[:,cols_new]

# to find the memory usage of the columns by memory _usage
original_memory= cols2.memory_usage(deep = True)
original_memory

KeyError: "None of [['fractal_dimension_worst', 'smoothness_worst', 'texture_worst', 'diagnosis']] are in the [columns]"

In [65]:
cols2.head()
cols2.dtypes

fractal_dimension_worst     float64
smoothness_worst            float64
texture_worst               float64
diagnosis                  category
dtype: object

In [67]:
#converting to a different data type using astype
#not all the columns could be converted to a data type .if a column has some missing values such as nanvalues ,it cant be converted to int dtype
#all missing values are of float64 dtype
#any column of integer dtype has a missing value will be changed ie is that column will be  of float value 
cols2['fractal_dimension_worst']=cols2['fractal_dimension_worst'].astype(np.int8)

In [68]:
original_memory= cols2.memory_usage(deep = True)
original_memory
# the memory usage is reduced to 569 from 4552 for this column

Index                        80
fractal_dimension_worst     569
smoothness_worst           4552
texture_worst              4552
diagnosis                   773
dtype: int64

In [69]:
# to save even more memory ,the object dtype are converted to category dtype
#'object' dtype contains a mix of integers strings list tuples or timestamps in its colums 
#this is done by finding the number of unique values of columns of object dtype
#in this example only one column is object dtype ie diagnosis
df['diagnosis'].nunique()

2

In [70]:
#convert this to category data
cols2['diagnosis'] = cols2['diagnosis'].astype('category')
original_memory= cols2.memory_usage(deep = True)
original_memory

Index                        80
fractal_dimension_worst     569
smoothness_worst           4552
texture_worst              4552
diagnosis                   773
dtype: int64

In [ ]:
#Lastly, it is possible to see the enormous memory difference between the minimal RangeIndex and Int64Index,
#which stores every row index in memory

#Int64 index is the immutable array with index and values (eg panda data frame)
#default index type in pandas when index is not specified

#rangeindex is the default index for object dtype and helps in memory usage

In [80]:
##selecting column with methods 2nd chapter
#get_dtype_counts gives the number of columns in a specified dtype
df.get_dtype_counts()
#select_dtypes to select only particular dtype
df.select_dtypes(include = ['int','float']).head()
#to select numeric columns alone by including 'number '
df.select_dtypes(include  = ['number']).head()
#filter method returns the columns by finding the column names and not the actual data values
#it has three parameters items,like,regex
df.filter(like ='mean')

,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean
0,17.990,10.38,122.80,1001.0,0.11840,0.27760,0.300100,0.147100,0.2419,0.07871
1,20.570,17.77,132.90,1326.0,0.08474,0.07864,0.086900,0.070170,0.1812,0.05667
2,19.690,21.25,130.00,1203.0,0.10960,0.15990,0.197400,0.127900,0.2069,0.05999
3,11.420,20.38,77.58,386.1,0.14250,0.28390,0.241400,0.105200,0.2597,0.09744
4,20.290,14.34,135.10,1297.0,0.10030,0.13280,0.198000,0.104300,0.1809,0.05883
5,12.450,15.70,82.57,477.1,0.12780,0.17000,0.157800,0.080890,0.2087,0.07613
6,18.250,19.98,119.60,1040.0,0.09463,0.10900,0.112700,0.074000,0.1794,0.05742
7,13.710,20.83,90.20,577.9,0.11890,0.16450,0.093660,0.059850,0.2196,0.07451
8,13.000,21.82,87.50,519.8,0.12730,0.19320,0.185900,0.093530,0.2350,0.07389
9,12.460,24.04,83.97,475.9,0.11860,0.23960,0.227300,0.085430,0.2030,0.08243
10,16.020,23.24,102.70,797.8,0.08206,0.06669,0.032990,0.033230,0.1528,0.05697
11,15.780,17.89,103.60,781.0,0.09710,0.12920,0.099540,0.066060,0.1842,0.06082
12,19.170,24.80,132.40,1123.0,0.09740,0.24580,0.206500,0.111800,0.2397,0.07800
13,15.850,23.95,103.70,782.7,0.08401,0.10020,0.099380,0.053640,0.1847,0.05338
14,13.730,22.61,93.60,578.3,0.11310,0.22930,0.212800,0.080250,0.2069,0.07682
15,14.540,27.54,96.73,658.8,0.11390,0.15950,0.163900,0.073640,0.2303,0.07077
16,14.680,20.13,94.74,684.5,0.09867,0.07200,0.073950,0.052590,0.1586,0.05922
17,16.130,20.68,108.10,798.8,0.11700,0.20220,0.172200,0.102800,0.2164,0.07356
18,19.810,22.15,130.00,1260.0,0.09831,0.10270,0.147900,0.094980,0.1582,0.05395
19,13.540,14.36,87.46,566.3,0.09779,0.08129,0.066640,0.047810,0.1885,0.05766
20,13.080,15.71,85.63,520.0,0.10750,0.12700,0.045680,0.031100,0.1967,0.06811
21,9.504,12.44,60.34,273.9,0.10240,0.06492,0.029560,0.020760,0.1815,0.06905
22,15.340,14.26,102.50,704.4,0.10730,0.21350,0.207700,0.097560,0.2521,0.07032
23,21.160,23.04,137.20,1404.0,0.09428,0.10220,0.109700,0.086320,0.1769,0.05278
24,16.650,21.38,110.00,904.6,0.11210,0.14570,0.152500,0.091700,0.1995,0.06330
25,17.140,16.40,116.00,912.7,0.11860,0.22760,0.222900,0.140100,0.3040,0.07413
26,14.580,21.53,97.41,644.8,0.10540,0.18680,0.142500,0.087830,0.2252,0.06924
27,18.610,20.25,122.10,1094.0,0.09440,0.10660,0.149000,0.077310,0.1697,0.05699
28,15.300,25.27,102.40,732.4,0.10820,0.16970,0.168300,0.087510,0.1926,0.06540
29,17.570,15.05,115.00,955.1,0.09847,0.11570,0.098750,0.079530,0.1739,0.06149
...,...,...,...,...,...,...,...,...,...,...
539,7.691,25.44,48.34,170.4,0.08668,0.11990,0.092520,0.013640,0.2037,0.07751
540,11.540,14.44,74.65,402.9,0.09984,0.11200,0.067370,0.025940,0.1818,0.06782
541,14.470,24.99,95.81,656.4,0.08837,0.12300,0.100900,0.038900,0.1872,0.06341
542,14.740,25.42,94.70,668.6,0.08275,0.07214,0.041050,0.030270,0.1840,0.05680
543,13.210,28.06,84.88,538.4,0.08671,0.06877,0.029870,0.032750,0.1628,0.05781
544,13.870,20.70,89.77,584.8,0.09578,0.10180,0.036880,0.023690,0.1620,0.06688
545,13.620,23.23,87.19,573.2,0.09246,0.06747,0.029740,0.024430,0.1664,0.05801
546,10.320,16.35,65.31,324.9,0.09434,0.04994,0.010120,0.005495,0.1885,0.06201
547,10.260,16.58,65.85,320.8,0.08877,0.08066,0.043580,0.024380,0.1669,0.06714
548,9.683,19.34,61.05,285.7,0.08491,0.05030,0.023370,0.009615,0.1580,0.06235
549,10.820,24.21,68.89,361.6,0.08192,0.06602,0.015480,0.008160,0.1976,0.06328
550,10.860,21.48,68.51,360.5,0.07431,0.04227,0.000000,0.000000,0.1661,0.05948
551,11.130,22.44,71.49,378.4,0.09566,0.08194,0.048240,0.022570,0.2030,0.06552
552,12.770,29.43,81.35,507.9,0.08276,0.04234,0.019970,0.014990,0.1539,0.05637
553,9.333,21.94,59.01,264.0,0.09240,0.05605,0.039960,0.012820,0.1692,0.06576
554,12.880,28.92,82.50,514.3,0.08123,0.05824,0.061950,0.023430,0.1566,0.05708
555,10.290,27.61,65.67,321.4,0.09030,0.07658,0.059990,0.027380,0.1593,0.06127
556,10.160,19.59,64.73,311.7,0.10030,0.07504,0.005025,0.011160,0.1791,0.06331
557,9.423,27.88,59.26,271.3,0.08123,0.04971,0.000000,0.000000,0.1742,0.06059
558,14.590,22.68,96.39,657.1,0.08473,0.13300,0.102900,0.037360,0.1454,0.06147
559,11.510,23.93,74.52,403.5,0.09261,0.10210,0.111200,0.041050,0.1388,0.06570
560,14.050,27.15,91.38,600.4,0.09929,0.11260,0.044620,0.043040,0.1537,0.06171
561,11.200,29.37,70.67,386.0,0.07449,0.03558,0.000000,0.000000,0.1060,0.05502
562,15.220,30.62,103.40,716.9,0.10480,0.20870,0.255000,0.094290,0.2128,0.07152
563,20.920,25.09,143.00,1347.0,0.10990,0.22360,0.317400,0.147400,0.2149,0.06879
564,21.560,22.39,142.00,1479.0,0.11100,0.11590,0.243900,0.138900,0.1726,0.05623
565,20.130,28.25,131.20,1261.0,0.09780,0.10340,0.144000,0.097910,0.1752,0.05533
566,16.600,28.08,108.30,858.1,0.08455,0.10230,0.092510,0.053020,0.1590,0.05648
567,20.600,29.33,140.10,1265.0,0.11780,0.27700,0.351400,0.152000,0.2397,0.07016
568,7.760,24.54,47.92,181.0,0.05263,0.04362,0.000000,0.000000,0.1587,0.05884

In [3]:
#Selecting smallest from the largest ie find the top 'n values' in a coulmn and find the bottom m values based on a different column
movie = pd.read_csv(r"C:\Users\SRIVIDHYA\Desktop\movie_metadata.csv")
movie.head(10).T
movie2 =movie[['imdb_score','budget','movie_title']]
# drop the missing values
movie2.dropna(axis= 0,how = 'any',inplace = True)
#inplace = True returns none and false  makes a copy of the object with the opeartionperformed.
movie2.head(5)
# find the movies that are in top 100 based on imdb score and with low budget(top 5)
#nlargest has a paramter keep that  takes first ,last,all.
#first keeps the first occurence of the duplicate rows
#last keeps the last occurence of the duplicate rows
#all keeps all rows
movie2.nlargest(100,'imdb_score').nsmallest(5,'budget').head()

#columns parameter with list of  column names takes the nlargest and nsmallest methods when there are duplicates values share the nth rank place in the first column in the list

C:\Users\SRIVIDHYA\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

      imdb_score    budget                 movie_title
4937         8.4  150000.0  A Charlie Brown Christmas
4924         8.7  180000.0             Butterfly Girl
4921         8.5  180000.0         Children of Heaven
4822         8.9  350000.0               12 Angry Men
4659         8.4  500000.0               A Separation

In [13]:
#Select the largest of each group by sorting

movie3 = movie[['movie_title','title_year','imdb_score']]
#sort values based on movie year and score put in a list by sort_values  method that sorts multiple columns in a time
movie4 = movie3.sort_values(['title_year','imdb_score'],ascending = False)
movie4.head()

                       movie_title  title_year  imdb_score
4409         Kickboxer: Vengeance       2016.0         9.1
4372  A Beginner's Guide to Snuff       2016.0         8.7
3870                      Airlift       2016.0         8.5
27     Captain America: Civil War       2016.0         8.2
98            Godzilla Resurgence       2016.0         8.2

In [15]:
# drop the duplicates of each year just keeping the first row of each year
#drop_duplicates keeps the first occurence of unique row 

movie_to_year = movie4.drop_duplicates(subset='title_year')
movie_to_year.head(10)

                                   movie_title  title_year  imdb_score
4409                     Kickboxer: Vengeance       2016.0         9.1
3816                          Running Forever       2015.0         8.6
4468                   Queen of the Mountains       2014.0         8.7
4017  Batman: The Dark Knight Returns, Part 2       2013.0         8.4
3                       The Dark Knight Rises       2012.0         8.5
3931                                  Samsara       2011.0         8.5
97                                  Inception       2010.0         8.8
67                                         Up       2009.0         8.3
66                            The Dark Knight       2008.0         9.0
2686                                    U2 3D       2007.0         8.4

In [16]:
#to ascend one column and descend another column
movie5 = movie[['movie_title','title_year','content_rating','budget']]
#sort values based on movie year and score put in a list by sort_values  method that sorts multiple columns in a time,give the boolean values in ascending
movie6 = movie5.sort_values(['title_year','content_rating','budget'],ascending = [False,True,False])
movie6.head()

                           movie_title  title_year content_rating       budget
3309                      The Wailing       2016.0      Not Rated          NaN
4400                      Cabin Fever       2016.0      Not Rated          NaN
79                    The Jungle Book       2016.0             PG  175000000.0
1805                  The Jungle Book       2016.0             PG  175000000.0
106   Alice Through the Looking Glass       2016.0             PG  170000000.0

In [18]:
# find the movies that are in top 100 based on imdb score and with low budget(top 5) but by using sort_values ...instead of nlargest and nsmallest
#movie2.nlargest(100,'imdb_score').nsmallest(5,'budget').head()
movie2.sort_values('imdb_score',ascending = False).head(100).sort_values('budget').head()

      imdb_score    budget                 movie_title
4937         8.4  150000.0  A Charlie Brown Christmas
4924         8.7  180000.0             Butterfly Girl
4921         8.5  180000.0         Children of Heaven
4822         8.9  350000.0               12 Angry Men
4748         8.4  500000.0       The Other Dream Team

In [7]:
#read data from google import data reader
#to find the trailing stop order price given with the initial purchase price of a stock

#import pandas_datareader as pdr
#tsla = pdr.DataReader('tsla',data_source= 'google',start = '2017-1-1')
#tsla.head()
#error

ImmediateDeprecationError:
Google finance has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues